### ISSUE TITLE
Debug project_count bug on simulation page

### ISSUE THREAD

**Issue by rusty-chris** [Superscriptus/DemoApp#20]
2021-10-15 07:25:03.337 Traceback (most recent call last):
  File "/home/expert/Documents/contracting/SS/DemoApp/venv/lib/python3.6/site-packages/streamlit/script_runner.py", line 349, in _run_script
    exec(code, module.__dict__)
  File "/home/expert/Documents/contracting/SS/DemoApp/superscript_app.py", line 26, in <module>
    app.execute()
  File "/home/expert/Documents/contracting/SS/DemoApp/application.py", line 36, in execute
    set_default_parameters()
  File "/home/expert/Documents/contracting/SS/DemoApp/pages/simulation.py", line 231, in set_default_parameters
    st.session_state[key] = value
  File "/home/expert/Documents/contracting/SS/DemoApp/venv/lib/python3.6/site-packages/streamlit/state/session_state.py", line 502, in __setitem__
    state[key] = value
  File "/home/expert/Documents/contracting/SS/DemoApp/venv/lib/python3.6/site-packages/streamlit/state/session_state.py", line 325, in __setitem__
    f"`st.session_state.{key}` cannot be modified after the widget"
streamlit.errors.StreamlitAPIException: `st.session_state.project_count` cannot be modified after the widget with key `project_count` is instantiated.

2021-10-15 07:26:27.741 Traceback (most recent call last):
  File "/home/expert/Documents/contracting/SS/DemoApp/venv/lib/python3.6/site-packages/streamlit/script_runner.py", line 349, in _run_script
    exec(code, module.__dict__)
  File "/home/expert/Documents/contracting/SS/DemoApp/superscript_app.py", line 26, in <module>
    app.execute()
  File "/home/expert/Documents/contracting/SS/DemoApp/application.py", line 36, in execute
    set_default_parameters()
  File "/home/expert/Documents/contracting/SS/DemoApp/pages/simulation.py", line 231, in set_default_parameters
    st.session_state[key] = value
  File "/home/expert/Documents/contracting/SS/DemoApp/venv/lib/python3.6/site-packages/streamlit/state/session_state.py", line 502, in __setitem__
    state[key] = value
  File "/home/expert/Documents/contracting/SS/DemoApp/venv/lib/python3.6/site-packages/streamlit/state/session_state.py", line 325, in __setitem__
    f"`st.session_state.{key}` cannot be modified after the widget"
streamlit.errors.StreamlitAPIException: `st.session_state.project_count` cannot be modified after the widget with key `project_count` is instantiated.

**Comment by rusty-chris** [comment]
Fixed bug 16/10/21
